### ISSUE TITLE
Bukkit/Spigot 1.8 Combatibility?

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#34]
Hi Catageek, 
Any chance you update Bytecart to be 1.8 Bukkit / Spigot combatible?

If tested it on 1.8, as i want to switch from 1.7.9 to 1.8+, but it dosent work. i can get a ticket from the signs, but routers wont switch :(

would be nice if you could make it work with 1.8+.

**Comment by dewick** [comment]
Looks like it can't read from books
[code][ERROR] Could not pass event VehicleMoveEvent to ByteCart v2.7.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.EntityMinecartAbstract.s_(EntityMinecartAbstract.java:318) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1604) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.World.g(World.java:1579) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1422) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException: at index 24
        at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftMetaBook.getPages(CraftMetaBook.java:243) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at com.github.catageek.ByteCart.FileStorage.BookInputStream.readPages(BookInputStream.java:41) ~[?:?]
        at com.github.catageek.ByteCart.FileStorage.BookInputStream.<init>(BookInputStream.java:20) ~[?:?]
        at com.github.catageek.ByteCart.FileStorage.BookFile.getInputStream(BookFile.java:132) ~[?:?]
        at com.github.catageek.ByteCart.Routing.RoutingTableFactory.getRoutingTable(RoutingTableFactory.java:35) ~[?:?]
        at com.github.catageek.ByteCart.Signs.BC8010.<init>(BC8010.java:67) ~[?:?]
        at com.github.catageek.ByteCart.Signs.TriggeredSignFactory.getTriggeredIC(TriggeredSignFactory.java:119) ~[?:?]
        at com.github.catageek.ByteCart.Signs.TriggeredSignFactory.getTriggeredIC(TriggeredSignFactory.java:37) ~[?:?]
        at com.github.catageek.ByteCart.EventManagement.ByteCartListener.onVehicleMove(ByteCartListener.java:84) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        ... 13 more[/code]

**Comment by catageek** [comment]
I need to take some time to check that. I never tried the spigot version of craftbukkit.

**Comment by thiefa** [comment]
take yoour time.
thank you for keeping the plugin up and running :)

**Comment by catageek** [comment]
I have good news and bad news.

The good news is that I found the first issues with 1.8 and they can be solved.

The bad news is that MC1.8 broke the books and they must be regenerated. The books in the chest above routers must be manually deleted. Thanks to the bcupdater command, they will be automatically created with an updater cart.

The other bad news is that this [bug](http://www.spigotmc.org/threads/signs-loose-brackets-on-1-8-update.39374/) affects all ByteCart signs and broke my test world. Be sure to use the fix of spigot when converting a 1.7 world to 1.8 if you don't want to break things.

**Comment by thiefa** [comment]
well,
i can live with the book deleting thing.
anyway have expanded my network and need to run a full update.

now i just need a good solution for updating networks across worlds, but i guess i will use fake router, with the others world network ip, and after the backbone has been updated with the fake router ip, i will set back the teleport-signs :)

**Comment by catageek** [comment]
I am now stopped at the redstone not updated when a lever is switched. The lever is actually updated, but the redstone is not. I am not sure to find a workaround for this one as I used an obscure trick that bergerkiller was using in TrainCarts and it does not work anymore.
Unfortunately bergerkiller did not update his plugins and there is no documentation on how to replace this trick.

If you know some plugins that switch levers and that were updated recently let me know to check their code.

**Comment by thiefa** [comment]
ok,
will keep my eyes open

**Comment by Welfare93** [comment]
Could you please point us to the section of code where you switch lever?
I am not sure, so this is just a idea. With 1.8 and new metadata system is possible that switching lever by old system (Lever a; a.setData(a.getData() ^ 0x8); //switching lever with XOR) dont work correctly. Did you try to switch it by new metadata system (Block state)? http://minecraft.gamepedia.com/Lever

**Comment by catageek** [comment]
The code that switch the lever is [here](https://github.com/catageek/ByteCart/blob/master/src/com/github/catageek/ByteCart/IO/ComponentLever.java#L27). The last line tries to force the physics update of the block where the lever is attached.

It calls a code where the trick is [here](https://github.com/catageek/ByteCartAPI/blob/master/src/com/github/catageek/ByteCartAPI/Util/MathUtil.java#L83). It used to work with bukkit <= 1.7.

**Comment by catageek** [comment]
please try [this](http://bytecart.catageek.info/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/2.8.1-SNAPSHOT/ByteCart-2.8.1-20150308.004256-1.jar). It should work. It worked in my test server.

Don't forget to delete all the books in the chest above the router and launch the region updaters in each region to regenerate them. local updaters are not needed in this case. Books from 1.7 world will cause NullPointerExceptions if you forget to remove them.

If the brackets were removed from the signs during the upgrade to 1.8, set FixBroken18 to true in config.yml to fix them automatically when the carts pass on them.

**Comment by thiefa** [comment]
hi catageek, 
thank you for your effort on that :)

i cant download, seems the file name or location are wrong.. im getting an 404.
"Error 404 - Not found

Le fichier requis n'a pas été trouvé. Il peut s'agir d'une erreur technique. Veuillez réessayer ultérieurement. Si vous ne pouvez pas accéder au fichier après plusieurs tentatives, cela signifie qu'il a été supprimé. "

**Comment by catageek** [comment]
the link was fixed

**Comment by catageek** [comment]
I advise strongly to backup your world because existing books are causing issues and I had to restore. An old ticket corrupted a chunk. It is mandatory to destroy all books because they are too unstable.

**Comment by thiefa** [comment]
oki, will test on a copy.. 
thanks for the reminder

**Comment by dewick** [comment]
catageek: Can we delete all corrupted books somehow with updater? We have quite a lot of routers and stations (http://map.majncraft.cz/?worldname=world_nether&mapname=nether&zoom=4&x=-145&y=64&z=-335) and I can't imagine removing books one by one :(

**Comment by thiefa** [comment]
@dewick:

nice network..
mines on http://pia.hopto.org:8123

how did you manage to color the trainlines??? want that to :D

**Comment by dewick** [comment]
@thiefa: Thanks, these are just lines drawn from dynmap by using dmarker one by one by one guy :)

**Comment by thiefa** [comment]
oh.. sounds like pain in the *** :D

hoped you maybe manged to get  http://dev.bukkit.org/bukkit-plugins/dyntrack/ working, as this should exactly do that ;)

**Comment by catageek** [comment]
@dewick here is a new [snapshot](http://bytecart.catageek.info/maven/repositories/snapshots/com/github/catageek/ByteCart/2.8.1-SNAPSHOT/ByteCart-2.8.1-20150308.134709-2.jar) that tries to detect corrupted books and remove them.

Try it with an updater: it should not trigger NullPointerException and put a readable book in the chest.

I already saw your network by googling Bytecart. I also saw your DNS, and I always wonder why you did not use the API to catch name resolution request (check [this](https://github.com/catageek/ByteCartAPI/blob/master/src/com/github/catageek/ByteCartAPI/ByteCartAPI.java)).

**Comment by catageek** [comment]
Hmmm... Everything go to the garbage collector now, except updaters. Expect some new fix later.

**Comment by thiefa** [comment]
true for your first update

cant say for the second one, right now running the updater with some routers that i didnt have removed the books to check if it works well.

**Comment by catageek** [comment]
new [snapshot](http://bytecart.catageek.info/maven/repositories/snapshots/com/github/catageek/ByteCart/2.8.1-SNAPSHOT/ByteCart-2.8.1-20150308.214413-3.jar) that fix the routing layers. Books have now color codes automatically inserted, and it broke the tickets decoding. Stripping color codes fix it.

Everything is OK now ?

**Comment by thiefa** [comment]
hi, 
yes seems all to work just fine.
i  give it a go for public release :)

thank you so very mutch :)

1.8, here i am ;)



PS: any way to show my thankfullness?

**Comment by dewick** [comment]
Not working for us, our bcupdater keeps glitching, looping and ranomly stopping. But I guess it is not ByteCarts fault, but we have some malfunction designs on our BC network that needs to be fixed first :)

Thanks catgeek!

btw.: could you add some kind of detailed info for messages like these? "Tilted sign found. Please straight it up in the axis of the track" - At least world coordinates so we can find issues faster.

**Comment by thiefa** [comment]
@dewick:
im sure i saw the coordinates for the wrongly orientated signs when mine was screwed. if i remember right ( sorry, i could be wrong, quite some time ago..) it was pretty mutch at the bottom of the error.


@catageek:
to add to dewick's wish:
a way to find the updaters on track would be nice.
either a command to get coordinates of the updater, like "bcupdater region x / backbone where" or kinda placing fakeplayers in the updaters, that are called like the updater so dynmap shows those "players" on the map.

id prefer both at once :D

would make finding updaters easier, if one gets stuck, or to check if a reseter stil is on track.
dynmap has a pluginin to show carts, but that only goes for moving ones, and if an updater is stuck for some reason (glitched out in corners, stuck in corners...) it wont be displayed anymore.

its alot work checking every singel tunnel to be sure theres nothing on track anymore.

**Comment by dewick** [comment]
@thiefa A little helpful is https://github.com/webbukkit/Dynmap-Diag addon for Dynmap. It shows loaded chunks, so if you are lucky, you can somehow track down where bcupdater could be riding at the moment. But it is really inaccurate and hunting down moving updater is really pain in the ass :p

**Comment by thiefa** [comment]
@dewick 
dynmap-mobs http://dev.bukkit.org/bukkit-plugins/dynmap-mobs/ does exactly that.. it shows a cart icon on map and gets updated like moving players (a little less frequent), so everyone can track the cart.
thats nice and alot helpfull aslong as the cart is moving, but the cart will vanish from the map if its not moving anymore for what reason ever, and thats where the troubel starts..

**Comment by catageek** [comment]
@dewick message for tilted signs was added in the [release](http://bytecart.catageek.info/maven/repositories/releases/com/github/catageek/ByteCart/2.8.1/ByteCart-2.8.1.jar). Also, I have an updater that is turning in my network since yesterday without problem, so your problem is not the plugin.

@thiefa You or someone else already asked me that, and I did not have time to implement it. IIRC it is not so easy, that's why it is not done yet.

**Comment by dewick** [comment]
@thiefa Just one interresting thing I made. I recorded updater for ~10hours and made a timelapse video (thanks to loaded chunks and dynmap-mobs plugin). It looks kinda interresting how the updater is driving around the network :D

https://www.youtube.com/watch?v=EWMuOu2La1Y

**Comment by thiefa** [comment]
cool vid :)
i often watched the updater on my dynmap, but it looks really nice this way :)

**Comment by catageek** [comment]
Nice !

I will take the opportunity of this thread to talk about another topic: A server community that I had known some time ago wants to reboot its map. They need a transit system but are afraid about ByteCart that they find complicated.

http://stonelegion.com/threads/stone-legion-reborn-looking-for-ideas-and-suggestions.2698/

May I suggest you to create an account on their forum a put a testimonial message on how you managed the project internally since the beginning ? How many people did participate to build the network ? Were they skilled in networking ? I can't talk about these points myself.

Otherwise use this thread to testify, and I will link your message, but it will difficult to open a discussion.

Thanks a lot in advance !
