### ISSUE TITLE
Minecraft 1.11.2 errors

### ISSUE THREAD

**Issue by ardentcrest** [catageek/ByteCart#43]
I'm getting 

> 
23:08:00] [Server thread/ERROR]: Error occurred while enabling ByteCart v2.9.4 (Is it up to date?)
java.lang.NullPointerException
	at com.github.catageek.ByteCart.plugins.BCHostnameResolutionPlugin.onLoad(BCHostnameResolutionPlugin.java:60) ~[?:?]
	at com.github.catageek.ByteCart.ByteCart.onEnable(ByteCart.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-b32c8f8-46226d6]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

> 

will the pluging still work. and will you be updating it

**Comment by thiefa** [comment]
Hi, 
im Running on Spigot 1.11.2 too (just did the last version Update Yesterday) and i dont get that error.
My Java version is build 1.8.0_112-b15

**Comment by ardentcrest** [comment]
mine is (build 1.8.0_121-b13)

**Comment by catageek** [comment]
Hi,
It's probably because the Hostname Resolution plugin does not find the SQL provider. Select the right provider in the config file (it will default to sqlite if you don't mention explicitly 'mysql').
If you don't have a SQL provider, or don't want to use it, disable hostname resolution.

**Comment by ardentcrest** [comment]
TY.
