### ISSUE TITLE
Error when carts get over an 8010 router

### ISSUE THREAD

**Issue by thiefa** [catageek/ByteCart#50]
hi gatageek,
i get errors like this when a cart enters (only some?? ) old 8010 routers:

`Caused` by: java.io.EOFException: End of input at line 600 column 16
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1377) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:73) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        at com.github.catageek.ByteCart.Routing.RoutingTableFactory.getRoutingTable(RoutingTableFactory.java:45) ~[?:?]
        at com.github.catageek.ByteCart.Signs.BC8010.loadChest(BC8010.java:70) ~[?:?]
        at com.github.catageek.ByteCart.Signs.BC8010.<init>(BC8010.java:60) ~[?:?]
        at com.github.catageek.ByteCart.Signs.TriggeredSignFactory.getTriggeredIC(TriggeredSignFactory.java:119) ~[?:?]
        at com.github.catageek.ByteCart.Signs.TriggeredSignFactory.getTriggeredIC(TriggeredSignFactory.java:37) ~[?:?]
        at com.github.catageek.ByteCart.EventManagement.ByteCartListener.onVehicleMove(ByteCartListener.java:85) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
        ... 13 `more`

**Comment by catageek** [comment]
Hi thiefa,

This is probably an error in the format of the routing table. Please remove the book in routers where you get the error and run 'bcupdater region' to rebuild the routing table. I think this will fix the error.

Tell me if I'm wrong.

catageek

**Comment by thiefa** [comment]
hi catageek, 
that's the solution i came up with too.

while its working, and im running an updater, i still wonder why the tables got screwed up in the first place..


so while this is solved, i abuse this issue page to add some suggestions aswell.. i repost as a new issue if you prefer.

for a future bc release:
1: is there a way to make bc aware of where updaters are, and add a command to locate/teleport to them and or remove them at once? (them cause different regions...)

2: also any way to add an option to set the speed of bc7006 respectively bc7007?  so i cant set a bc7007 to say: 1 1/2 vanilla speed, but when passing an bc7006 they can be like 3 times vanilla? helps on large networks...

3: while i know its way out of what bc does and thus prolly never will  do it into bc:
a way to add transworld teleportation and bungee transportation? (while i have tested plugins that allow that, they are somewhat unprecise on putting the cart on track, and it happens you end up somewhere bad, also teleportation of (chest)carts (updaters) dont work all the time.. :( )

4: got some issues with dynmap as Mr_killer01 allready posted on spigot, but on top of that , there always has been an issue with the updater signs not getting properly removed from dynmap when the cart timeouted, or got removed while the cart was on track but stuck somewhere.

**Comment by catageek** [comment]
Hi @thiefa,

Thanks for the report. I am not currently in a Dev run because of IRL summer activities. I keep the ticket open as a reminder.

You can use 'bcupdater remove' to remove the updater property of a cart when it will pass on any BC sign. This does not remove physically the cart, but stops the update immediately.

For the point 3, I am afraid I will not put this in my TODO list.

Catageek

**Comment by thiefa** [comment]
thank you so mutch for that /bcupdater remove !! 
saves hours on checking for updaters when the updater icons vanish!

Sidenote: 
with dynmap 2.5 updaters are visible again, even on the run..
however, it still happens that after some time the icon disappears, even if the updater is on a run... 
not sure if its when he runs in a timeout, or something else...

also i still have that java error... i deleted the router table from almost any router, but it seems having just one with a corrupt table keeps screwing up the others.. i run updater on one comp (with a testuser in cart behind to keep track of updater) and me keep logged in to tp to the user asap i get that error, deleting the table, so when the carts get back, the router is proper...

just cant get rid of that thing :(

**Comment by catageek** [comment]
For the corrupted table, could you check the book in the router that triggers the error and tell if something is missing (a bracket, a comma or a parenthesis) ? I wonder if the json format is compatible with the book, because the error tells that this is not the json file expected. The binary format never caused an issue, maybe I should revert to it.

**Comment by thiefa** [comment]
hi catageek, 
sorry for the long delay.
was updating to 1.12 aswell, so running your latest update and spigot 1.12.
just updated everthing like an hour ago.

as for the error: still having it..

took out the book on a faulty router (50 pages, yay..)

so far anything looked well, besides the last page witch is left "open":
it ends with:
"155": {
 "routes": {
   "173": [

so it seems it dosent close the brackets, for what reason ever? as there should be direction coming next, right?


any helpfull?
sorry, not really understanding mutch of that things...

**Comment by catageek** [comment]
Hi @thiefa 

I think you're right about the 50 pages hard limit, it is documented and I did not really took it in consideration. Your server has more routes than my test server.

I think I will revert to the binary format when there are more than 50 pages to avoid this.

**Comment by catageek** [comment]
@thiefa 

Please  try this [fix](http://catageek.free.fr/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/3.1.2-SNAPSHOT/ByteCart-3.1.2-20170619.193355-1.jar)

Please put `debug = true` in the config file, remove the corrupted books and run `bcupdater region`. The routing tables should be JSON-formatted at first, then in binary format when 50 pages are reached.

If you got an error, please dump the log here.

**Comment by thiefa** [comment]
Hi catageek, 
Still had the error somewhen this night.
Unfortunatly i was asleep at that time and did not set debug to true, so i cant deliver the routers table or debug info.

i set debug to true now and let the updater run just as i write this lines.. will keep an eye on it, so i see where it breaks to have a look at the router table and time of the error to give you the right snipped of log file...

**Comment by thiefa** [comment]
[21:51:39 WARN]: java.io.IOException
[21:51:39 WARN]:        at com.github.catageek.ByteCart.FileStorage.BookOutputStream.flush(BookOutputStream.java:82)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.FileStorage.ItemStackMetaOutputStream.flush(ItemStackMetaOutputStream.java:45)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.FileStorage.BookFile.flush(BookFile.java:172)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Routing.RoutingTableBookJSON.serialize(RoutingTableBookJSON.java:326)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Updaters.AbstractRegionUpdater.routeUpdates(AbstractRegionUpdater.java:86)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Updaters.UpdaterRegion.Update(UpdaterRegion.java:182)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Updaters.AbstractRegionUpdater.doAction(AbstractRegionUpdater.java:100)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Signs.BC8010.trigger(BC8010.java:172)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.EventManagement.ByteCartListener.onVehicleMove(ByteCartListener.java:95)
[21:51:39 WARN]:        at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
[21:51:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:51:39 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[21:51:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:51:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:51:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[21:51:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.EntityMinecartAbstract.B_(EntityMinecartAbstract.java:328)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1608)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:51:39 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:51:39 INFO]: ByteCart : doAction() : current is 97
[21:51:39 INFO]: Book has too many pages
[21:51:39 WARN]: java.io.IOException
[21:51:39 WARN]:        at com.github.catageek.ByteCart.FileStorage.BookOutputStream.flush(BookOutputStream.java:82)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.FileStorage.ItemStackMetaOutputStream.flush(ItemStackMetaOutputStream.java:45)
[21:51:39 WARN]:        at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1823)
[21:51:39 WARN]:        at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Wanderer.WandererContentFactory.saveContent(WandererContentFactory.java:130)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Updaters.UpdaterContentFactory.saveContent(UpdaterContentFactory.java:62)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Updaters.AbstractRegionUpdater.doAction(AbstractRegionUpdater.java:114)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.Signs.BC8010.trigger(BC8010.java:172)
[21:51:39 WARN]:        at com.github.catageek.ByteCart.EventManagement.ByteCartListener.onVehicleMove(ByteCartListener.java:95)
[21:51:39 WARN]:        at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
[21:51:39 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:51:39 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[21:51:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:51:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:51:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[21:51:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.EntityMinecartAbstract.B_(EntityMinecartAbstract.java:328)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1608)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1434)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:51:39 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:51:39 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:51:39 INFO]: ByteCart: loading player inventory :test_user111
[21:51:39 INFO]: ByteCart: BC7007.trigger()
[21:51:39 INFO]: ByteCart: loading player inventory :test_user111
[21:51:39 INFO]: ByteCart: BC8010.trigger()
[21:51:39 INFO]: ByteCart: property string : 836
[21:51:39 INFO]: ByteCart: BookProperties : setting key net.ttl to 835
[21:51:39 INFO]: ByteCart: property string : 835

**Comment by thiefa** [comment]
the book this happens has 33 pages and is all binary.. it ends with "AAAAAAAAAA="

**Comment by catageek** [comment]
Thanks @thiefa 

What I see is that the routing table is fixed for the moment, but the issue is with the updater that try to store a book with more than 50 pages, and triggers an exception (instead of failing silently as before)

What i don't understand is that it used to work before.

Could you please give me the previous log similar to this one before 21:21:17:

> [21:51:17] [Server thread/INFO]: ByteCart : Flushing 6274 bytes of data to meta
> [21:51:17] [Server thread/INFO]: ByteCart : Flushing meta to itemstack

what I want to see is how many bytes are stored in the updater.

**Comment by thiefa** [comment]
Hi catageek, 
thats the bytecart message befor the error:
[21:50:34] [Server thread/INFO]: ByteCart: BC7006.trigger()
[21:50:34] [Server thread/INFO]: ByteCart: loading player inventory :test_user111
[21:50:34] [Server thread/INFO]: ByteCart: BC7006.trigger()
[21:50:36] [Server thread/INFO]: ByteCart: BC7007.trigger()
[21:50:36] [Server thread/INFO]: ByteCart: BC8010.trigger()
[21:50:36] [Server thread/INFO]: ByteCart : selectDirection() : minimum counter 4
[21:50:36] [Server thread/INFO]: ByteCart : Router : coming from EAST going to NORTH
[21:50:36] [Server thread/INFO]: ByteCart : getOrSetCurrent() : current as track on sign 90
[21:50:36] [Server thread/INFO]: ByteCart : Update() : current is 90
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 197, metric = 188, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 157, metric = 106, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 95, metric = 288, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 98, metric = 306, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 107, metric = 288, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 108, metric = 229, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 110, metric = 106, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 111, metric = 229, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 113, metric = 121, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 115, metric = 163, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Update : ring = 127, metric = 106, direction EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 19 with metric 134 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 48 with metric 134 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 49 with metric 134 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 50 with metric 80 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 51 with metric 80 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 52 with metric 29 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 65 with metric 330 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 66 with metric 241 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 77 with metric 29 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 78 with metric 29 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 79 with metric 24 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 80 with metric 87 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 81 with metric 87 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 82 with metric 87 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 83 with metric 100 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 86 with metric 100 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 87 with metric 100 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 88 with metric 24 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 89 with metric 24 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 90 with metric 0 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 93 with metric 0 to SOUTH
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 94 with metric 0 to WEST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 95 with metric 288 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 98 with metric 306 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 104 with metric 191 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 105 with metric 191 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 106 with metric 191 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 107 with metric 288 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 108 with metric 229 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 110 with metric 106 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 111 with metric 229 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 113 with metric 121 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 115 with metric 163 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 127 with metric 106 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 145 with metric 241 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 146 with metric 241 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 147 with metric 278 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 157 with metric 106 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 163 with metric 198 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 174 with metric 278 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 175 with metric 278 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Route exchange : give ring 197 with metric 188 to EAST
[21:50:36] [Server thread/INFO]: ByteCart : Flushing 6287 bytes of data to meta
[21:50:36] [Server thread/INFO]: ByteCart : Flushing meta to itemstack
[21:50:36] [Server thread/INFO]: ByteCart : doAction() : current is 90
[21:50:36] [Server thread/INFO]: ByteCart : Flushing 5004 bytes of data to meta
[21:50:36] [Server thread/INFO]: ByteCart : Flushing meta to itemstack
[21:50:36] [Server thread/INFO]: ByteCart: loading player inventory :test_user111
[21:50:36] [Server thread/INFO]: ByteCart: BC7007.trigger()
[21:50:36] [Server thread/INFO]: ByteCart: loading player inventory :test_user111
[21:50:36] [Server thread/INFO]: ByteCart: BC8010.trigger()
[21:50:36] [Server thread/INFO]: ByteCart: property string : 842
[21:50:36] [Server thread/INFO]: ByteCart: BookProperties : setting key net.ttl to 841
[21:50:36] [Server thread/INFO]: ByteCart: property string : 841
[21:50:36] [Server thread/INFO]: ByteCart : TTL is 841
[21:50:36] [Server thread/INFO]: ByteCart : Flushing 71 bytes of data to meta
[21:50:36] [Server thread/INFO]: ByteCart : Flushing meta to itemstack
[21:50:36] [Server thread/INFO]: ByteCart : update player inventory
[21:50:36] [Server thread/INFO]: ByteCart : Router : coming from EAST going to NORTH
[21:50:38] [Server thread/INFO]: ByteCart: BC7006.trigger()


i did upload the full log to my server, if you want it, but be warned, some plugins spam the log..
[Logfile](http://pia.hopto.org/minecraft/2017-06-20-2.log)

**Comment by catageek** [comment]
I made a [fix](http://catageek.free.fr/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/3.1.2-SNAPSHOT/ByteCart-3.1.2-20170621.214321-3.jar) for the routing table, but unfortunately the updater need more work. It has reached its maximum capacity on your server.

As a workaround, the updater is invalidated if it is corrupted to avoid the corruption of routing tables. Relaunching it from various parts should allow to complete the configuration.

I really need to spend a few hours on a more serious fix, but it will take a few weeks.

**Comment by thiefa** [comment]
sorry for making you so mutch work :(

but great plugins need alot work ;)

**Comment by thiefa** [comment]
hi catageek, 
i'm still trying to update the network, running carts from different locations on the network, but pretty soon after launch (when it hits an already updated router) i get this:

`[23:25:03] [Server thread/INFO]: ByteCart : Route exchange : give ring 166 with metric 384 to SOUTH
[23:25:03] [Server thread/INFO]: ByteCart : Route exchange : give ring 168 with metric 384 to SOUTH
[23:25:03] [Server thread/INFO]: ByteCart : Route exchange : give ring 174 with metric 694 to SOUTH
[23:25:03] [Server thread/INFO]: ByteCart : Route exchange : give ring 175 with metric 694 to SOUTH
[23:25:03] [Server thread/INFO]: ByteCart : Route exchange : give ring 197 with metric 617 to SOUTH
[23:25:03] [Server thread/INFO]: ByteCart: Trying to store in JSON format
[23:25:03] [Server thread/INFO]: ByteCart : Flushing 6845 bytes of data to meta
[23:25:03] [Server thread/INFO]: ByteCart : Flushing meta to itemstack
[23:25:03] [Server thread/INFO]: ByteCart : doAction() : current is 99
**[23:25:03] [Server thread/INFO]: 64 pages are needed, maximum is 50**
**[23:25:03] [Server thread/INFO]: Bytecart: I/O error (maximum capacity reached), updater deleted`**


i know we nailed the issue to json rather than the old binary saving.. 
its still a pain :(
any chance for an ETA on a fix?


on the next line: 
while binary may save some space, im pretty sure it still would reach the 50 page hardcap before the theoretical limit of bc, so i think the entire store process has to be done in a way witch respect that 50 page hardcap? 
like placing a link to an external file in the book, rather the file itself?


hope to hear soon some good news ;)

have a nice time

**Comment by catageek** [comment]
Hi @thiefa 
My plan is to put books in all the slots available, which will multiply by 27 the capacity.

The reason why the file is in the book is because the book can cross inter-server portals. An on-server storage would break the inter-server capacity.

I will try to release a development version before the 5th of august.

**Comment by thiefa** [comment]
hi catageek, 
thanks for the explanation, 
makes alot sense, i did not thought about inter-server, even when i use a bungee myself *shame on me*


gona cuddle you, if you could manage it (even if it gets later then 5. august)  ;)


greetz thiefa

**Comment by catageek** [comment]
Hi @thiefa 

Please test [this](http://catageek.free.fr/bytecart/maven/repositories/snapshots/com/github/catageek/ByteCart/3.1.2-SNAPSHOT/ByteCart-3.1.2-20170728.220730-5.jar), it should work now. I expanded the storage to all slots, and I add books if needed. I made some unit tests that worked perfectly, now let's see how it works in real life.

catageek

**Comment by thiefa** [comment]
hi catageek, 
updater is on a run, so far everything goes well.

ill post tomorrow evening the results, going for a nap now, and let him run..

*pre-cuddles catageek" ;)
